### ISSUE TITLE
Invalid link or wrong song

### ISSUE THREAD

**Issue by ghost** [kostas214/SpotifyDownloader#3]
While trying to use the app I have 2 possiblities:
1. It matches the wrong song. That was in the song section where I tried https://open.spotify.com/track/25brT5xsqdKuoZqvz3Ubrn?si=_i1Bv9V9TyCNSQxgcbGruQ&context=spotify%3Aplaylist%3A37i9dQZF1EIY4Rv0gzAXkr and the was giving me  a unrelated song 
2. In the playlist and album section I get invalid link. Try for example https://open.spotify.com/track/25brT5xsqdKuoZqvz3Ubrn?si=_i1Bv9V9TyCNSQxgcbGruQ&context=spotify%3Aplaylist%3A37i9dQZF1EIY4Rv0gzAXkr. Its not a problem if it won't get solved but I just wanted to notify

**Comment by kostas214** [comment]
Hello thank you for opening an issue ticket.

It appears that the problem is with my user interface and the instructions or rather lack of instructions i have provided. 

The "Song Download" tab actually works with the name (and preferably the artist name )of the song not the spotify share link in the next update i will be greatly improving the  "Song Download" tab and adding a README.md on the Github page 

As far as for the second issue it appears that the link you have provided isn't actually a playlist nor an album so that's why it causes an issue 

Valid album and playlist links for example are 
```https://open.spotify.com/album/3tFjhFPqGhhLrCULnPu7Wy?si=zdIP-mU9Qfa_3VKtwcjFvQ```
```https://open.spotify.com/playlist/0F042Hz0yupm7ODPChB5AZ?si=ab5e2c25c9bb4005```

and you can find them by tapping the 3 dots on the top of the album/playlist page and clicking copy link.


Thank you for your input i never expected i will get a user and i will be implementing the fixes mentioned above as soon as possible

**Comment by kostas214** [comment]
Hello,
So the update wasn't as complicated as i thought and i was able to finish it today. If you look in the releases there is a new version so please update to it

**Comment by ghost** [comment]
Thanks for the response

**Comment by ghost** [comment]
It works as expected. If it would be possible to share a link with Spotifydownloader  from a other app using the share button to not be required to open the app manually  and if spotfy song urls could be  used  instead of song names that would be fun. But right now the app does what it says it is doing so it's great
